// Local compatibility types used by the remaining legacy UI seams.
// Keep this file limited to types that are still consumed by the application.
export type GooseExtension =
  | {
      name: string;
      description?: string | null;
      display_name?: string | null;
      timeout?: number | null;
      bundled?: boolean | null;
      /**
       * Tool allowlist for this extension. Omit this field to allow all tools.
       */
      available_tools?: Array<string> | null;
      type: 'builtin';
    }
  | {
      name: string;
      description?: string | null;
      display_name?: string | null;
      bundled?: boolean | null;
      /**
       * Tool allowlist for this extension. Omit this field to allow all tools.
       */
      available_tools?: Array<string> | null;
      type: 'platform';
    }
  | {
      server: McpServer;
      envKeys?: Array<string>;
      description?: string | null;
      timeout?: number | null;
      socket?: string | null;
      bundled?: boolean | null;
      /**
       * Tool allowlist for this extension. Omit this field to allow all tools.
       */
      available_tools?: Array<string> | null;
      type: 'mcp';
    };
/**
 * Configuration for connecting to an MCP (Model Context Protocol) server.
 *
 * MCP servers provide tools and context that the agent can use when
 * processing prompts.
 *
 * See protocol docs: [MCP Servers](https://agentclientprotocol.com/protocol/session-setup#mcp-servers)
 */
export type McpServer = McpServerHttp | McpServerSse | McpServerAcp | McpServerStdio;
/**
 * An HTTP header to set when making requests to the MCP server.
 */
export type HttpHeader = {
  /**
   * The name of the HTTP header.
   */
  name: string;
  /**
   * The value to set for the HTTP header.
   */
  value: string;
  /**
   * The _meta property is reserved by ACP to allow clients and agents to attach additional
   * metadata to their interactions. Implementations MUST NOT make assumptions about values at
   * these keys.
   *
   * See protocol docs: [Extensibility](https://agentclientprotocol.com/protocol/extensibility)
   */
  _meta?: {
    [key: string]: unknown;
  } | null;
};
/**
 * HTTP transport configuration for MCP.
 */
export type McpServerHttp = {
  /**
   * Human-readable name identifying this MCP server.
   */
  name: string;
  /**
   * URL to the MCP server.
   */
  url: string;
  /**
   * HTTP headers to set when making requests to the MCP server.
   */
  headers: Array<HttpHeader>;
  /**
   * The _meta property is reserved by ACP to allow clients and agents to attach additional
   * metadata to their interactions. Implementations MUST NOT make assumptions about values at
   * these keys.
   *
   * See protocol docs: [Extensibility](https://agentclientprotocol.com/protocol/extensibility)
   */
  _meta?: {
    [key: string]: unknown;
  } | null;
  type: 'http';
};
/**
 * SSE transport configuration for MCP.
 */
export type McpServerSse = {
  /**
   * Human-readable name identifying this MCP server.
   */
  name: string;
  /**
   * URL to the MCP server.
   */
  url: string;
  /**
   * HTTP headers to set when making requests to the MCP server.
   */
  headers: Array<HttpHeader>;
  /**
   * The _meta property is reserved by ACP to allow clients and agents to attach additional
   * metadata to their interactions. Implementations MUST NOT make assumptions about values at
   * these keys.
   *
   * See protocol docs: [Extensibility](https://agentclientprotocol.com/protocol/extensibility)
   */
  _meta?: {
    [key: string]: unknown;
  } | null;
  type: 'sse';
};
/**
 * **UNSTABLE**
 *
 * This capability is not part of the spec yet, and may be removed or changed at any point.
 *
 * Unique identifier for an MCP server using the ACP transport.
 *
 * The value is opaque and generated by the ACP component providing the MCP server. It is
 * used by `mcp/connect` to route connection requests back to the component that declared the
 * server.
 */
export type McpServerAcpId = string;
/**
 * **UNSTABLE**
 *
 * This capability is not part of the spec yet, and may be removed or changed at any point.
 *
 * ACP transport configuration for MCP.
 *
 * The MCP server is provided by an ACP component and communicates over the ACP channel
 * using `mcp/connect`, `mcp/message`, and `mcp/disconnect`.
 */
export type McpServerAcp = {
  /**
   * Human-readable name identifying this MCP server.
   */
  name: string;
  /**
   * Unique identifier for this MCP server, generated by the component providing it.
   *
   * Providers MUST NOT reuse an ID for multiple ACP-transport MCP servers that are visible
   * on the same ACP connection.
   */
  id: McpServerAcpId;
  /**
   * The _meta property is reserved by ACP to allow clients and agents to attach additional
   * metadata to their interactions. Implementations MUST NOT make assumptions about values at
   * these keys.
   *
   * See protocol docs: [Extensibility](https://agentclientprotocol.com/protocol/extensibility)
   */
  _meta?: {
    [key: string]: unknown;
  } | null;
};
/**
 * Stdio transport configuration for MCP.
 */
export type McpServerStdio = {
  /**
   * Human-readable name identifying this MCP server.
   */
  name: string;
  /**
   * Path to the MCP server executable.
   */
  command: string;
  /**
   * Command-line arguments to pass to the MCP server.
   */
  args: Array<string>;
  /**
   * Environment variables to set when launching the MCP server.
   */
  env: Array<EnvVariable>;
  /**
   * The _meta property is reserved by ACP to allow clients and agents to attach additional
   * metadata to their interactions. Implementations MUST NOT make assumptions about values at
   * these keys.
   *
   * See protocol docs: [Extensibility](https://agentclientprotocol.com/protocol/extensibility)
   */
  _meta?: {
    [key: string]: unknown;
  } | null;
};
/**
 * An environment variable to set when launching an MCP server.
 */
export type EnvVariable = {
  /**
   * The name of the environment variable.
   */
  name: string;
  /**
   * The value to set for the environment variable.
   */
  value: string;
  /**
   * The _meta property is reserved by ACP to allow clients and agents to attach additional
   * metadata to their interactions. Implementations MUST NOT make assumptions about values at
   * these keys.
   *
   * See protocol docs: [Extensibility](https://agentclientprotocol.com/protocol/extensibility)
   */
  _meta?: {
    [key: string]: unknown;
  } | null;
};
/**
 * A single tool item returned by the tools list endpoint.
 */
export type ToolListItem = {
  name: string;
  description: string;
  parameters: Array<string>;
  permission?: ToolPermissionLevel | null;
  inputSchema: unknown;
  outputSchema?: unknown;
};
/**
 * Permission level for a tool.
 */
export type ToolPermissionLevel = 'always_allow' | 'ask_before' | 'never_allow';
/**
 * A single tool permission entry.
 */
export type ToolPermissionEntry = {
  toolName: string;
  permission: ToolPermissionLevel;
};
export type SteerSessionResponse_unstable = {
  runId: string;
  /**
   * Stable id of the queued steer message. The same id later appears as
   * `messageId` on the streamed `UserMessageChunk` (with `_meta.goose.steer`),
   * letting clients correlate a queued steer with its pickup.
   */
  messageId: string;
};
export type GooseExtensionEntry = {
  extension: GooseExtension;
  enabled: boolean;
  configKey?: string | null;
};
export type ProviderTemplateCatalogEntryDto = {
  providerId: string;
  name: string;
  format: string;
  apiUrl: string;
  modelCount: number;
  docUrl: string;
  envVar: string;
};
export type ProviderTemplateDto = {
  providerId: string;
  name: string;
  format: string;
  apiUrl: string;
  models: Array<ProviderTemplateModelDto>;
  supportsStreaming: boolean;
  envVar: string;
  docUrl: string;
};
export type ProviderTemplateModelDto = {
  id: string;
  name: string;
  contextLimit: number;
  capabilities: ProviderTemplateCapabilitiesDto;
  deprecated: boolean;
};
export type ProviderTemplateCapabilitiesDto = {
  toolCall: boolean;
  reasoning: boolean;
  attachment: boolean;
  temperature: boolean;
};
export type ProviderConfigStatusDto = {
  providerId: string;
  isConfigured: boolean;
};
export type CustomProviderReadResponse_unstable = {
  provider: CustomProviderConfigDto;
  editable: boolean;
  status: ProviderConfigStatusDto;
};
export type CustomProviderConfigDto = {
  providerId: string;
  engine: string;
  displayName: string;
  apiUrl: string;
  models?: Array<string>;
  supportsStreaming?: boolean | null;
  headers?: {
    [key: string]: string;
  };
  requiresAuth: boolean;
  catalogProviderId?: string | null;
  basePath?: string | null;
  apiKeyEnv?: string | null;
  apiKeySet: boolean;
  preservesThinking: boolean;
};
export type ProviderSecretDto = {
  id: string;
  provider: string;
  providerDisplayName: string;
  name: string;
  storage: ProviderSecretStorageDto;
  expiresAt?: string | null;
  status: ProviderSecretStatusDto;
  configured: boolean;
  hasSecret: boolean;
  canDelete: boolean;
  canConfigure: boolean;
  configureProvider?: string | null;
};
export type ProviderSecretStorageDto = 'secret_store' | 'provider_cache';
export type ProviderSecretStatusDto = 'valid' | 'expired' | 'unknown';
export type CanonicalModelInfoDto = {
  provider: string;
  model: string;
  contextLimit: number;
  maxOutputTokens?: number | null;
  reasoning: boolean;
  inputTokenCost?: number | null;
  outputTokenCost?: number | null;
  cacheReadTokenCost?: number | null;
  cacheWriteTokenCost?: number | null;
  currency: string;
};
export type RecipeExtensionDto =
  | {
      name: string;
      description?: string | null;
      display_name?: string | null;
      timeout?: number | null;
      bundled?: boolean | null;
      /**
       * Tool allowlist for this extension. Omit this field to allow all tools.
       */
      available_tools?: Array<string> | null;
      type: 'builtin';
    }
  | {
      name: string;
      description?: string | null;
      display_name?: string | null;
      bundled?: boolean | null;
      /**
       * Tool allowlist for this extension. Omit this field to allow all tools.
       */
      available_tools?: Array<string> | null;
      type: 'platform';
    }
  | {
      name: string;
      description?: string | null;
      cmd: string;
      args?: Array<string>;
      envs?: {
        [key: string]: string;
      };
      env_keys?: Array<string>;
      timeout?: number | null;
      cwd?: string | null;
      bundled?: boolean | null;
      /**
       * Tool allowlist for this extension. Omit this field to allow all tools.
       */
      available_tools?: Array<string> | null;
      type: 'stdio';
    }
  | {
      name: string;
      description?: string | null;
      uri: string;
      envs?: {
        [key: string]: string;
      };
      env_keys?: Array<string>;
      headers?: {
        [key: string]: string;
      };
      timeout?: number | null;
      socket?: string | null;
      bundled?: boolean | null;
      /**
       * Tool allowlist for this extension. Omit this field to allow all tools.
       */
      available_tools?: Array<string> | null;
      type: 'streamable_http';
    };
/**
 * The type of source entity.
 */
export type SourceType = 'skill' | 'builtinSkill' | 'recipe' | 'subrecipe' | 'agent' | 'project';
/**
 * A source discovered by Goose. Filesystem sources use an on-disk path;
 * built-in sources use a stable synthetic path. Sources may be either
 * `global` (shared across all projects) or project-specific.
 */
export type SourceEntry = {
  type: SourceType;
  name: string;
  description: string;
  content: string;
  /**
   * Stable on-disk path identifying this source. Pass it back to
   * update/delete/export to operate on this entry. Skills use the directory
   * containing `SKILL.md`; projects use the project file path; built-in
   * skills use `builtin://skills/<name>` synthetic paths.
   */
  path: string;
  /**
   * True when the source lives in the user's global sources directory; false
   * when it lives inside a specific project.
   */
  global: boolean;
  /**
   * True when this source can be modified through source CRUD methods.
   * Client-provided bundled sources are returned as read-only.
   */
  writable?: boolean;
  /**
   * Paths (absolute) of additional files that live alongside the source.
   * Only skills currently populate this; empty for other source types.
   */
  supportingFiles?: Array<string>;
  /**
   * Arbitrary key/value pairs for type-specific metadata (e.g. icon, color,
   * preferredProvider for projects). Stored in the frontmatter.
   */
  properties?: {
    [key: string]: unknown;
  };
};
/**
 * A user-facing `@` mention target backed by an agent, recipe, or subrecipe source.
 */
export type AgentMention = {
  name: string;
  description: string;
  sourceType: SourceType;
  sourcePath?: string | null;
  mention: string;
};
/**
 * Information about a command.
 */
export type AvailableCommand = {
  /**
   * Command name (e.g., `create_plan`, `research_codebase`).
   */
  name: string;
  /**
   * Human-readable description of what the command does.
   */
  description: string;
  /**
   * Input for the command if required
   */
  input?: AvailableCommandInput | null;
  /**
   * The _meta property is reserved by ACP to allow clients and agents to attach additional
   * metadata to their interactions. Implementations MUST NOT make assumptions about values at
   * these keys.
   *
   * See protocol docs: [Extensibility](https://agentclientprotocol.com/protocol/extensibility)
   */
  _meta?: {
    [key: string]: unknown;
  } | null;
};
/**
 * All text that was typed after the command name is provided as input.
 */
export type AvailableCommandInput = UnstructuredCommandInput;
/**
 * All text that was typed after the command name is provided as input.
 */
export type UnstructuredCommandInput = {
  /**
   * A hint to display when the input hasn't been provided yet
   */
  hint: string;
  /**
   * The _meta property is reserved by ACP to allow clients and agents to attach additional
   * metadata to their interactions. Implementations MUST NOT make assumptions about values at
   * these keys.
   *
   * See protocol docs: [Extensibility](https://agentclientprotocol.com/protocol/extensibility)
   */
  _meta?: {
    [key: string]: unknown;
  } | null;
};
/**
 * Per-provider configuration status.
 */
export type DictationProviderStatusEntry = {
  configured: boolean;
  host?: string | null;
  description: string;
  usesProviderConfig: boolean;
  settingsPath?: string | null;
  configKey?: string | null;
  modelConfigKey?: string | null;
  defaultModel?: string | null;
  selectedModel?: string | null;
  availableModels?: Array<DictationModelOption>;
};
export type DictationModelOption = {
  id: string;
  label: string;
  description: string;
};
export type DictationLocalModelStatus = {
  id: string;
  label: string;
  description: string;
  sizeMb: number;
  downloaded: boolean;
  downloadInProgress: boolean;
  recommended: boolean;
};
export type DictationDownloadProgress = {
  bytesDownloaded: number;
  totalBytes: number;
  progressPercent: number;
  /**
   * serde lowercase of DownloadStatus: "downloading" | "completed" | "failed" | "cancelled"
   */
  status: string;
  error?: string | null;
};
export type LocalInferenceModelDto = {
  id: string;
  repoId: string;
  filename: string;
  quantization: string;
  sizeBytes: number;
  status: LocalInferenceModelDownloadStatusDto;
  recommended: boolean;
  isLoaded: boolean;
  settings: LocalInferenceModelSettingsDto;
  visionCapable: boolean;
  mmprojStatus?: LocalInferenceModelDownloadStatusDto | null;
};
export type LocalInferenceModelDownloadStatusDto = {
  state: LocalInferenceDownloadState;
  progressPercent?: number | null;
  bytesDownloaded?: number | null;
  totalBytes?: number | null;
  speedBps?: number | null;
};
export type LocalInferenceDownloadState = 'NotDownloaded' | 'Downloading' | 'Downloaded';
export type LocalInferenceModelSettingsDto = {
  backendId?: string | null;
  contextSize?: number | null;
  maxOutputTokens?: number | null;
  draftModel?: string | null;
  sampling?: LocalInferenceSamplingConfig;
  repeatPenalty: number;
  repeatLastN: number;
  frequencyPenalty: number;
  presencePenalty: number;
  nBatch?: number | null;
  nGpuLayers?: number | null;
  useMlock: boolean;
  flashAttention?: boolean | null;
  nThreads?: number | null;
  toolCalling?: LocalInferenceToolCallingMode;
  chatTemplate?: LocalInferenceChatTemplate;
  enableThinking: boolean;
  visionCapable: boolean;
  imageTokenEstimate: number;
  mmprojSizeBytes: number;
};
export type LocalInferenceSamplingConfig =
  | {
      type: 'Greedy';
    }
  | {
      temperature: number;
      topK: number;
      topP: number;
      minP: number;
      seed?: number | null;
      type: 'Temperature';
    }
  | {
      tau: number;
      eta: number;
      seed?: number | null;
      type: 'MirostatV2';
    };
export type LocalInferenceToolCallingMode = 'auto' | 'force_native' | 'force_emulated';
export type LocalInferenceChatTemplate =
  | {
      type: 'embedded';
    }
  | {
      name: string;
      type: 'builtin';
    }
  | {
      template: string;
      type: 'custom_inline';
    };
export type LocalInferenceModelDownloadRequest_unstable = {
  spec: string;
  backendId?: string | null;
  variantId?: string | null;
};
export type LocalInferenceDownloadProgressDto = {
  modelId: string;
  status: string;
  bytesDownloaded: number;
  totalBytes: number;
  progressPercent: number;
  speedBps?: number | null;
  etaSeconds?: number | null;
  error?: string | null;
  taskExited: boolean;
};
export type LocalInferenceHfModelInfoDto = {
  repoId: string;
  author: string;
  modelName: string;
  downloads: number;
  ggufFiles?: Array<LocalInferenceHfGgufFileDto>;
  variants?: Array<LocalInferenceHfModelVariantDto>;
};
export type LocalInferenceHfGgufFileDto = {
  filename: string;
  sizeBytes: number;
  quantization: string;
  downloadUrl: string;
};
export type LocalInferenceHfModelVariantDto = {
  variantId: string;
  label: string;
  backendId: string;
  format: string;
  modelId: string;
  downloadId: string;
  sizeBytes: number;
  filename?: string | null;
  downloadUrl?: string | null;
  description: string;
  qualityRank: number;
  sharded: boolean;
  supported: boolean;
  unsupportedReason?: string | null;
};
/**
 * Goose-custom session update notification — a parallel to ACP's
 * `session/update` carrying goose-specific update variants.
 */
export type GooseSessionNotification_unstable = {
  sessionId: string;
  update: GooseSessionUpdate;
};
/**
 * Discriminated union of goose-specific session update payloads.
 * Variant tag matches ACP's convention (`sessionUpdate: "<snake_case>"`).
 *
 * `discriminator.mapping` is what makes TS codegen (`@hey-api/openapi-ts`)
 * emit the correct snake_case tag value even when this enum has a single
 * variant. Add a mapping entry per variant.
 */
export type GooseSessionUpdate =
  | ({
      sessionUpdate: 'usage_update';
    } & SessionUsageUpdate)
  | ({
      sessionUpdate: 'status_message';
    } & StatusMessageUpdate)
  | ({
      sessionUpdate: 'message_usage';
    } & MessageUsageUpdate);
/**
 * Streaming context-window usage update for a session.
 */
export type SessionUsageUpdate = {
  used: number;
  contextLimit: number;
  accumulatedInputTokens: number;
  accumulatedOutputTokens: number;
  accumulatedCost?: number | null;
};
export type StatusMessage =
  | {
      message: string;
      type: 'notice';
    }
  | {
      message: string;
      type: 'progress';
    };
/**
 * Live UI/session status. This is not conversation transcript content, and
 * should not be persisted or replayed as history.
 */
export type StatusMessageUpdate = {
  status: StatusMessage;
};
/**
 * Wire mirror of the conversation `MessageUsage` (this crate cannot depend on
 * goose-provider-types); field names and serde casing MUST stay in parity.
 */
export type MessageUsageData = {
  inputTokens?: number | null;
  outputTokens?: number | null;
  totalTokens?: number | null;
  cacheReadTokens?: number | null;
  cacheWriteTokens?: number | null;
  cost?: number | null;
  costSource?: CostSourceData | null;
  /**
   * Wall-clock generation time, used by the client for a tokens/sec readout.
   */
  elapsedMs?: number | null;
  timeToFirstTokenMs?: number | null;
  /**
   * Usage from a compaction/summarization call rather than a normal turn.
   */
  isCompaction?: boolean;
};
/**
 * Wire mirror of the conversation `CostSource`.
 */
export type CostSourceData = 'provider_reported' | 'estimated';
/**
 * Per-message token usage/cost/timing, keyed by the message id used for
 * chunk matching. Sent live after a turn's messages and on replay.
 */
export type MessageUsageUpdate = {
  messageId?: string | null;
  usage: MessageUsageData;
};
